import { useEffect, useState } from 'react';

export default function BookingModal({ item, mode, onClose }) {
  const [form, setForm] = useState({name:'', email:'', phone:'', start:'', end:''});
  const [error, setError] = useState(''); const [done, setDone] = useState(false);
  useEffect(() => { const key = e => e.key === 'Escape' && onClose(); window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [onClose]);
  const update = e => setForm({...form, [e.target.name]:e.target.value});
  const submit = e => { e.preventDefault(); if (!form.name || !form.email || !form.phone || !form.start) return setError('Please complete the required fields.'); if (mode === 'vehicle' && !form.end) return setError('Choose a return date.'); const bookings = JSON.parse(localStorage.getItem('rentsphere-bookings') || '[]'); localStorage.setItem('rentsphere-bookings', JSON.stringify([...bookings, {item:item.id, mode, ...form, createdAt:new Date().toISOString()}])); const bookingType = mode === 'property' ? 'Property' : item.kind || 'Vehicle'; const bookingDetails = mode === 'property' ? `Date: ${form.start}` : `Pickup Date: ${form.start}\nReturn Date: ${form.end}`; const message = `RentSphere - ${bookingType} Booking Request\n\n${mode === 'property' ? 'Property' : 'Vehicle'}: ${item.title || item.name}\n${mode === 'vehicle' ? `Type: ${item.kind || item.type}\n` : ''}Location: ${item.location}\n\nCustomer Details:\nName: ${form.name}\nPhone: ${form.phone}\nEmail: ${form.email}\n\n${mode === 'property' ? 'Booking' : 'Rental'} Details:\n${bookingDetails}\n\nPlease confirm this ${mode === 'property' ? 'booking' : 'rental'}.`; const whatsappUrl = `https://wa.me/919403570134?text=${encodeURIComponent(message)}`; window.location.href = whatsappUrl; };
  return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="booking-modal" role="dialog" aria-modal="true" aria-labelledby="booking-heading" onMouseDown={e=>e.stopPropagation()}>{done ? <div className="booking-success"><div className="success-mark">✓</div><h2>WhatsApp is ready</h2><p>A chat has opened with your booking details pre-filled. Review the message and press Send in WhatsApp to submit it.</p><button className="btn btn-primary" onClick={onClose}>Done</button></div> : <><button className="modal-close" aria-label="Close booking" onClick={onClose}>×</button><span className="eyebrow">Booking request · step 1 of 1</span><h2 id="booking-heading">Reserve {item.title || item.name}</h2><p className="modal-subtitle">Share your details and we’ll prepare a WhatsApp booking request for you to send.</p><form onSubmit={submit} noValidate><div className="form-grid"><label>Full name<input name="name" value={form.name} onChange={update} placeholder="Your name" /></label><label>Email<input name="email" type="email" value={form.email} onChange={update} placeholder="you@example.com" /></label><label>Phone<input name="phone" value={form.phone} onChange={update} placeholder="10-digit mobile number" /></label><label>{mode === 'vehicle' ? 'Pickup date' : 'Move-in date'}<input name="start" type="date" value={form.start} onChange={update}/></label>{mode === 'vehicle' && <label>Return date<input name="end" type="date" value={form.end} min={form.start} onChange={update}/></label>}</div>{error && <p className="form-error" role="alert">{error}</p>}<button className="btn btn-primary full" type="submit">Continue to WhatsApp →</button></form></>}</section></div>;
}
